version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: dev

    image: app
    volumes:
      - ./app:/app
      - ./dump:/dump
    environment:
      NODE_ENV: dev
      DB_URI: postgres://dev:dev@db:5432/dev
      BOT_TOKEN: ''
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - db:/var/lib/postgresql/data:rw
      - ./dump:/dump



volumes:
  db: {}